// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUserIDError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UserID_ERROR.String() && e.Code == 405
}

func ErrorUserIDError(format string, args ...interface{}) *errors.Error {
	return errors.New(405, ErrorReason_UserID_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 406
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(406, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}
