## 修改这个文件要同步更改 internal 目录下的conf目录的pb文件
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3308)/test?charset=utf8mb4&parseTime=True
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  mongo:
    source: mongodb://localhost:27017
    db: test