// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMerchantComment = "merchant_comment"

// MerchantComment mapped from table <merchant_comment>
type MerchantComment struct {
	ID            uint64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`                    // 自增主键
	CreateAt      *time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"` // 创建时间
	UpdateAt      *time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_at"` // 更新时间
	Version       uint64     `gorm:"column:version;not null;comment:乐观锁" json:"version"`                                // 乐观锁
	MerchantID    int64      `gorm:"column:merchant_id;not null;comment:商家id" json:"merchant_id"`                       // 商家id
	CommentID     string     `gorm:"column:comment_id;not null;comment:评论id, uuid" json:"comment_id"`                   // 评论id, uuid
	LastCommentID string     `gorm:"column:last_comment_id;not null;comment:上一条评论id, uuid" json:"last_comment_id"`      // 上一条评论id, uuid
	Content       string     `gorm:"column:content;not null;comment:评价内容" json:"content"`                               // 评价内容
	SkuID         *string    `gorm:"column:sku_id;comment:商品sku_id" json:"sku_id"`                                      // 商品sku_id
}

// TableName MerchantComment's table name
func (*MerchantComment) TableName() string {
	return TableNameMerchantComment
}
