version: "3"

# run kafka service
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      # 允许使用kraft，即Kafka替代Zookeeper
      - KAFKA_ENABLE_KRAFT=yes
      # broker.id，必须唯一，且与KAFKA_CFG_NODE_ID一致
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      # kafka角色，做broker，也要做controller
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # 不允许自动创建主题
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      # controller 节点使用名为 CONTROLLER 的监听器进行通信
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # 配置的是broker之间通信使用的listener。这里设置为PLAINTEXT,表示broker之间数据复制也是明文传输。
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # 配置Kafka的多个listeners
      # 格式:LISTENER_NAME://HOST:PORT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      # 每个listener对应的安全协议
      # CONTROLLER listener使用PLAINTEXT
      # PLAINTEXT listener使用PLAINTEXT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # 广播给consumer的地址,让consumer连接
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${DOCKER_HOST_IP:-127.0.0.1}:9092
      # Leader 选举可以投票的结点，指定controller选举时需要联系和获取票数的broker节点，使用“broker_id@host:port”的格式
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      # 允许使用明文传输
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=7es-47FeQpCKpLfsN1uPxQ